name: C Command Line Interface Builder

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-execute:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Compile C program
      # Đảm bảo tên tệp main.c khớp với tên tệp bạn đã lưu mã nguồn C
      run: gcc -o tea_library main.c

    - name: Execute C program
      run: ./tea_library
